package application;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hussa
 */
public class LoginPage extends javax.swing.JFrame {

    DB db = new DB();
    static int durum ;
    
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMusteriNumarası = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        lblKayitOl = new javax.swing.JLabel();
        lblParolaSifirla = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_256.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Giriş"));

        jLabel2.setText("Müşteri Numarası :");

        txtMusteriNumarası.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMusteriNumarasıKeyPressed(evt);
            }
        });

        jLabel3.setText("Şifre :");

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        lblKayitOl.setText("Kayıt Ol");
        lblKayitOl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblKayitOlMouseMoved(evt);
            }
        });
        lblKayitOl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKayitOlMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKayitOlMouseExited(evt);
            }
        });

        lblParolaSifirla.setText("Parolamı Unuttum !");
        lblParolaSifirla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblParolaSifirlaMouseMoved(evt);
            }
        });
        lblParolaSifirla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblParolaSifirlaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblParolaSifirlaMouseExited(evt);
            }
        });

        txtSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSifreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblParolaSifirla)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSifre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMusteriNumarası, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKayitOl)
                                    .addComponent(btnGiris))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMusteriNumarası, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGiris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKayitOl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParolaSifirla)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void lblKayitOlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKayitOlMouseClicked
        YeniKayit yk = new YeniKayit();
        yk.setVisible(true);
    }//GEN-LAST:event_lblKayitOlMouseClicked

    private void lblKayitOlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKayitOlMouseMoved
        lblKayitOl.setForeground(Color.ORANGE);
    }//GEN-LAST:event_lblKayitOlMouseMoved

    private void lblKayitOlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKayitOlMouseExited
        lblKayitOl.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblKayitOlMouseExited

    private void lblParolaSifirlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParolaSifirlaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Pek Yakında...");
    }//GEN-LAST:event_lblParolaSifirlaMouseClicked

    private void lblParolaSifirlaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParolaSifirlaMouseMoved
        lblParolaSifirla.setForeground(Color.ORANGE);
    }//GEN-LAST:event_lblParolaSifirlaMouseMoved

    private void lblParolaSifirlaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParolaSifirlaMouseExited
        lblParolaSifirla.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblParolaSifirlaMouseExited


    static String loginMid = "";
    static String adminId = "1";
    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed

        loginMid = txtMusteriNumarası.getText();
        char[] sifDizi = txtSifre.getPassword();
        String sifre = String.valueOf(sifDizi);
        String gelenId = "";
        String gelenSifre = "";
        try {
            String idQuery = "select mid from musteriler where mid=" + loginMid ;
            ResultSet rsId = db.baglan().executeQuery(idQuery);
            gelenId = rsId.getString("mid");

        } catch (Exception e) {
            System.err.println("Data getirme hatası : " + e);
        } finally {
            db.kapat();
        }
        try {
            String girisQuery = "select mSifre from musteriler where mid=" + loginMid;
            ResultSet rsSifre = db.baglan().executeQuery(girisQuery);
            gelenSifre = rsSifre.getString("mSifre");
        } catch (Exception e) {
            System.err.println("Data getirme hatası : " + e);
        } finally {
            db.kapat();
        }

        if (loginMid.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen müşteri numaranızı giriniz");
            txtMusteriNumarası.requestFocus();
            txtMusteriNumarası.setText("");
        } else if (sifre.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen şifrenizi giriniz");
            txtSifre.requestFocus();
            txtSifre.setText("");
        } else if (!loginMid.equals(gelenId)) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı hatalı lütfen tekrar deneyiniz !");
            txtMusteriNumarası.setText("");
            txtSifre.setText("");
            txtMusteriNumarası.requestFocus();
        } else if (!sifre.equals(gelenSifre)) {
            JOptionPane.showMessageDialog(rootPane, "Şifre hatalı lütfen tekrar deneyiniz !");
            txtSifre.setText("");
            txtSifre.requestFocus();
        } else if (loginMid.equals(adminId)) {
            txtMusteriNumarası.setText("");
            txtSifre.setText("");
            durum = 1;
            AdminPage ap = new AdminPage();
            ap.setVisible(true);
            dispose();
        } else {
            txtMusteriNumarası.setText("");
            txtSifre.setText("");
            durum = 0;
            CustomerPage cp = new CustomerPage();
            cp.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtSifreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSifreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGirisActionPerformed(null);
        }
    }//GEN-LAST:event_txtSifreKeyPressed

    private void txtMusteriNumarasıKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMusteriNumarasıKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSifre.requestFocus();
        }
    }//GEN-LAST:event_txtMusteriNumarasıKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKayitOl;
    private javax.swing.JLabel lblParolaSifirla;
    private javax.swing.JTextField txtMusteriNumarası;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
